version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: techsivam16/goredishttps:latest
    ports:
      - "443:443"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD:
      REDIS_DB: "0"

  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis
